module.exports = [
    "Have you ever considered, that the problem is not them, but it’s you...?",
    "Newsflash, you will probably never win the lottery.",
    "Bugs may be nesting right now in your belly button lint.",
    "One day, your kid might have a stage name.",
    "You will lose a tooth.",
    "Your breath smells like pennies and burps.",
    "You will develop a hunchback. Not today, but soon.",
    "Shut your mouth when you’re talking to me!",
    "Meh, I’d say you’re about a 3½ or 4.",
    "You do not have mail.",
    "Someone is judging you right now.",
    "You will soon lose in battle to a measuring tape.",
    "Abracadabra! You are now allergic to pizza.",
    "Sorry, but your hair will keep falling out.",
    "Puppies hate you.",
    "You will have cold feet and hands from now until the end of time.",
    "When next you drink whiskey, you will laugh and it will come out your nose. Ouch!",
    "You will stub your toe someday.",
    "You are probably not your parents’ favorite child.",
    "Papercuts, lots of them coming your way.",
    "No soup for you!! ",
    "The bumper will fall off your car at some point.",
    "Glue and tape will never again stick for you.",
    "Survey says, you’re a tool.",
    "Congrats! Your interest rate just went up to 72.83%!",
    "We all have serious concerns about your future.",
    "Why are you always picked last for everything?!",
    "Your ears will grow to twice the size of your head. Good luck getting a date Dumbo.",
    "Your fly is down bozo.",
    "Your plants will always wither and die. Black Thumb!!",
    "Your car door will cease to shut properly from today until forever.",
    "You were the smelly kid in class.",
    "People think you’re gross. Like, fer real.",
    "You smell a bit like toe jam.",
    "You will develop an itch on your left butt cheek that will NEVER go away.",
    "Even your gramma feels bad for you.",
    "You won’t ever be cool.",
    "Your equilibrium will do a 180 and you will have to start walking only on your hands.",
    "May your grocery bags always have a hole in them.",
    "You will never develop patience. But everyone around you is developing oodles and oodles of it",
    "For you they’re sour, then they’re sour again.",
    "This Christmas Eve, elves might break into your house and slice up all your shoes. ",
    "May your right foot always be longer than the left. Good luck buying shoes.",
    "May your socks always be saggy.",
    "Public restroom stalls will always smell like farts for you.",
    "Have you ever considered that perhaps you were switched at birth?",
    "You will develop narcissistic tendencies.",
    "You’re about to send your dentist’s kids to college.",
    "Your radiator hoses are leaking.",
    "Even when you’ve stopped watching your pot, it’ll never boil.",
    "Your next haircut will be SOOO bad!",
    "Take a chance today! Drive home with your eyes closed!",
    "Your parents made a mistake.",
    "No one will swipe right for you.",
    "It will rain on your wedding day. Actually, who are we kidding, you will never get married.",
    "Everyone you know wishes they hadn’t met you.",
    "Beware of choking on a fortune cookie",
    "Error 404: Fortune not found",
    "Traffic in the lane next to you will ALWAYS move faster",
    "The fortune you seek is in another cookie",
    "Maybe it’s time for another therapy session?",
    "Your liver hates you.",
    "Your in laws will be in town for the foreseeable future."
];